services:
  java-maven-app:
    image: "prince450/demo-app:${TAG}"
    ports:
      - 8080:8080

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd